#!/bin/bash

# Setup script for HestiaCP proxy configuration
# This script helps configure HestiaCP to proxy to your Docker application

echo "🔧 Setting up HestiaCP proxy configuration..."

echo ""
echo "📋 Instructions for HestiaCP Configuration:"
echo "=========================================="
echo ""
echo "1. Go to HestiaCP → Web → portal.glab.si → Edit"
echo ""
echo "2. Change the following settings:"
echo "   - Web Template: APACHE2"
echo "   - Backend Template: PHP-FPM"
echo "   - Proxy Template: default"
echo "   - Proxy Extensions: Add 'php' to the list"
echo ""
echo "3. In the 'Proxy Support' section:"
echo "   - Enable Proxy Support: YES"
echo "   - Proxy Domain: portal.glab.si"
echo "   - Proxy Extensions: php,html,htm,js,css,ico,gif,jpg,jpeg,png,svg,woff,woff2,ttf,eot"
echo ""
echo "4. In the 'Proxy Configuration' section, add this configuration:"
echo "   Location: /"
echo "   Proxy URL: http://127.0.0.1:8088"
echo "   Proxy Extensions: php,html,htm,js,css,ico,gif,jpg,jpeg,png,svg,woff,woff2,ttf,eot"
echo ""
echo "5. For WebSocket support (Laravel Reverb), add:"
echo "   Location: /app/"
echo "   Proxy URL: http://127.0.0.1:8085"
echo "   Proxy Extensions: (leave empty)"
echo ""
echo "6. Save the configuration"
echo ""
echo "7. Restart the web service:"
echo "   sudo systemctl restart apache2"
echo ""
echo "✅ After completing these steps, your application should be accessible at:"
echo "   https://portal.glab.si"
echo ""
echo "🔍 To check if everything is working:"
echo "   - Docker containers: docker ps"
echo "   - Application logs: docker logs portal_app"
echo "   - Nginx logs: docker logs portal_nginx" 